"use client";

import type { SiteV3ModuleDescriptor, SiteV3ModuleCode } from "./site-v3-admin-types";

export const SITE_V3_MODULE_DESCRIPTORS: Record<SiteV3ModuleCode, SiteV3ModuleDescriptor> = {
  global_header: {
    moduleCode: "global_header",
    label: "Global header",
    category: "structure",
    description: "Brand header shared by the public Site V3 pages.",
    humanHint: "Use this for the site brand and account links. Usually one per page, placed at the top.",
    schemaVersion: 1,
    slotKeys: ["header"],
    fields: [
      {
        key: "brand_label",
        label: "Brand label",
        type: "string",
        group: "content",
        required: true,
        maxLength: 80,
        help: "Text shown as the site brand. Keep it short enough for mobile.",
      },
      {
        key: "login_label",
        label: "Login label",
        type: "string",
        group: "links",
        maxLength: 40,
        help: "Button copy linking to the existing V1 login route.",
      },
      {
        key: "account_label",
        label: "Account label",
        type: "string",
        group: "links",
        maxLength: 40,
        help: "Button copy linking to the existing V1 account route.",
      },
    ],
  },
  hero_banner: {
    moduleCode: "hero_banner",
    label: "Hero banner",
    category: "hero",
    description: "Primary homepage hero with headline, copy, CTA and optional media.",
    humanHint: "The main page banner. It can use a Site V3 media asset or fall back to the published V1 home banner.",
    schemaVersion: 1,
    slotKeys: ["main", "hero"],
    fields: [
      {
        key: "headline",
        label: "Headline",
        type: "string",
        group: "content",
        required: true,
        maxLength: 120,
        help: "Main headline. This is the first viewport message.",
      },
      {
        key: "body",
        label: "Body",
        type: "string",
        group: "content",
        maxLength: 500,
        help: "Supporting copy. Keep it concise and player-facing.",
      },
      {
        key: "cta_label",
        label: "CTA label",
        type: "string",
        group: "links",
        maxLength: 60,
        help: "Optional call-to-action text.",
      },
      {
        key: "cta_title_code",
        label: "CTA game",
        type: "title_code",
        group: "links",
        help: "Optional game title launched by the CTA. The backend validates the title.",
      },
      {
        key: "media_asset_ref",
        label: "Media asset",
        type: "asset_ref",
        group: "assets",
        help: "Optional banner asset. Pick a published Site media asset, or paste a public URL as fallback.",
      },
      {
        key: "show_copy",
        label: "Show copy",
        type: "boolean",
        group: "content",
        help: "Turn off to show only the banner image while keeping the CTA available.",
      },
      {
        key: "show_cta",
        label: "Show CTA",
        type: "boolean",
        group: "links",
        help: "Turn off to hide the banner button.",
      },
    ],
  },
  game_grid: {
    moduleCode: "game_grid",
    label: "Game grid",
    category: "catalog",
    description: "Grid of launchable game titles consumed from the live catalog.",
    humanHint: "The published game grid. Choose which title codes to show; the public order still follows the catalog.",
    schemaVersion: 1,
    slotKeys: ["main", "games"],
    fields: [
      {
        key: "heading",
        label: "Heading",
        type: "string",
        group: "content",
        required: true,
        maxLength: 100,
        help: "Heading above the game grid.",
      },
      {
        key: "title_codes",
        label: "Games",
        type: "title_code_list",
        group: "catalog",
        required: true,
        maxItems: 24,
        help: "Select launchable titles. The backend validates each title against the catalog.",
      },
    ],
  },
  game_grid_4x: {
    moduleCode: "game_grid_4x",
    label: "Grid$",
    category: "catalog",
    description: "Large four-column grid of launchable game titles.",
    humanHint: "Use this when game cards should be larger: four square cards per row on desktop, same catalog images.",
    schemaVersion: 1,
    slotKeys: ["main", "games"],
    fields: [
      {
        key: "heading",
        label: "Heading",
        type: "string",
        group: "content",
        required: true,
        maxLength: 100,
        help: "Heading above the large game grid.",
      },
      {
        key: "title_codes",
        label: "Games",
        type: "title_code_list",
        group: "catalog",
        required: true,
        maxItems: 24,
        help: "Select launchable titles. Rendered as four larger square cards per desktop row.",
      },
    ],
  },
  featured_game: {
    moduleCode: "featured_game",
    label: "Featured game",
    category: "catalog",
    description: "One highlighted launchable game with optional editorial copy.",
    humanHint: "One highlighted game, useful for promoting HI-LO, BOXE or a specific title variant.",
    schemaVersion: 1,
    slotKeys: ["main", "feature"],
    fields: [
      {
        key: "title_code",
        label: "Featured title",
        type: "title_code",
        group: "catalog",
        required: true,
        help: "The highlighted game title. Hidden or unavailable titles fail validation.",
      },
      {
        key: "headline",
        label: "Headline",
        type: "string",
        group: "content",
        maxLength: 120,
        help: "Optional custom headline. If empty, the renderer can use the title name.",
      },
      {
        key: "body",
        label: "Body",
        type: "string",
        group: "content",
        maxLength: 500,
        help: "Optional supporting copy for the featured game.",
      },
      {
        key: "cta_label",
        label: "CTA label",
        type: "string",
        group: "links",
        maxLength: 60,
        help: "Optional button copy.",
      },
    ],
  },
  promo_band: {
    moduleCode: "promo_band",
    label: "Promo band",
    category: "promo",
    description: "Editorial promo strip with headline, body and CTA URL.",
    humanHint: "A promotional or editorial strip. The MVP uses text and CTA only; upload remains in the asset area.",
    schemaVersion: 1,
    slotKeys: ["main", "promo"],
    fields: [
      {
        key: "headline",
        label: "Headline",
        type: "string",
        group: "content",
        required: true,
        maxLength: 120,
        help: "Promo title shown in the public band.",
      },
      {
        key: "body",
        label: "Body",
        type: "string",
        group: "content",
        maxLength: 500,
        help: "Promo description. Avoid legal or bonus promises not approved elsewhere.",
      },
      {
        key: "cta_label",
        label: "CTA label",
        type: "string",
        group: "links",
        maxLength: 60,
        help: "Optional CTA text.",
      },
      {
        key: "cta_url",
        label: "CTA URL",
        type: "string",
        group: "links",
        maxLength: 300,
        help: "Internal path or approved external URL. Backend validation is intentionally light in MVP.",
      },
    ],
  },
  rich_text_safe: {
    moduleCode: "rich_text_safe",
    label: "Rich text safe",
    category: "text_legal",
    description: "Allowlisted editorial HTML. The backend rejects unsafe tags and attributes.",
    humanHint: "Safe rich text for notes, rules, SEO or editorial content. HTML is filtered server-side.",
    schemaVersion: 1,
    slotKeys: ["main", "content", "footer"],
    fields: [
      {
        key: "html",
        label: "HTML",
        type: "html",
        group: "rules",
        required: true,
        maxLength: 12000,
        help: "Allowed tags: p, strong, em, ul, ol, li, a, br, h2, h3. No script/style/iframe.",
      },
    ],
  },
  global_footer: {
    moduleCode: "global_footer",
    label: "Global footer",
    category: "structure",
    description: "Footer legal text and link list shared by the public Site V3 pages.",
    humanHint: "Footer with legal text and links. Usually one per page, placed at the bottom.",
    schemaVersion: 1,
    slotKeys: ["footer"],
    fields: [
      {
        key: "legal_text",
        label: "Legal text",
        type: "string",
        group: "rules",
        required: true,
        maxLength: 1000,
        help: "Footer legal or responsible-gaming text.",
      },
      {
        key: "links",
        label: "Footer links",
        type: "nav_items",
        group: "links",
        maxItems: 12,
        help: "One link per line: label | URL path. Max 12.",
      },
    ],
  },
};

export const SITE_V3_MODULE_CODES = Object.keys(SITE_V3_MODULE_DESCRIPTORS) as SiteV3ModuleCode[];

export const SITE_V3_MODULE_CATEGORIES = [
  {
    key: "structure",
    label: "Global structure",
    description: "Shared page elements: header, navigation and footer.",
  },
  {
    key: "hero",
    label: "Hero and banners",
    description: "High-impact first-viewport modules for the main message.",
  },
  {
    key: "catalog",
    label: "Game catalog",
    description: "Modules connected to published titles and existing game cards in the catalog.",
  },
  {
    key: "promo",
    label: "Promos and editorial",
    description: "Promotional strips and lightweight editorial messages for the page.",
  },
  {
    key: "text_legal",
    label: "Text and legal",
    description: "Safe text areas, notes, SEO content and legal content.",
  },
] as const;
