"use client";

import type { SiteV3ModuleDescriptor, SiteV3ModuleCode } from "./site-v3-admin-types";

export const SITE_V3_MODULE_DESCRIPTORS: Record<SiteV3ModuleCode, SiteV3ModuleDescriptor> = {
  global_header: {
    moduleCode: "global_header",
    label: "Global header",
    description: "Navigation and brand header shared by the public Site V3 pages.",
    schemaVersion: 1,
    slotKeys: ["header"],
    fields: [
      {
        key: "brand_label",
        label: "Brand label",
        type: "string",
        required: true,
        maxLength: 80,
        help: "Text shown as the site brand. Keep it short enough for mobile.",
      },
      {
        key: "nav_items",
        label: "Navigation items",
        type: "nav_items",
        maxItems: 8,
        help: "One item per line: label | URL path, or label | title_code. Max 8.",
      },
      {
        key: "login_label",
        label: "Login label",
        type: "string",
        maxLength: 40,
        help: "Button copy linking to the existing V1 login route.",
      },
      {
        key: "account_label",
        label: "Account label",
        type: "string",
        maxLength: 40,
        help: "Button copy linking to the existing V1 account route.",
      },
    ],
  },
  hero_banner: {
    moduleCode: "hero_banner",
    label: "Hero banner",
    description: "Primary homepage hero with headline, copy, CTA and optional media.",
    schemaVersion: 1,
    slotKeys: ["main", "hero"],
    fields: [
      {
        key: "headline",
        label: "Headline",
        type: "string",
        required: true,
        maxLength: 120,
        help: "Main headline. This is the first viewport message.",
      },
      {
        key: "body",
        label: "Body",
        type: "string",
        maxLength: 500,
        help: "Supporting copy. Keep it concise and player-facing.",
      },
      {
        key: "cta_label",
        label: "CTA label",
        type: "string",
        maxLength: 60,
        help: "Optional call-to-action text.",
      },
      {
        key: "cta_title_code",
        label: "CTA game",
        type: "title_code",
        help: "Optional game title launched by the CTA. The backend validates the title.",
      },
      {
        key: "media_asset_ref",
        label: "Media asset",
        type: "asset_ref",
        help: "Optional asset reference. Use asset_id + asset_kind, or a public URL. Upload is a future WP.",
      },
    ],
  },
  game_grid: {
    moduleCode: "game_grid",
    label: "Game grid",
    description: "Grid of launchable game titles consumed from the live catalog.",
    schemaVersion: 1,
    slotKeys: ["main", "games"],
    fields: [
      {
        key: "heading",
        label: "Heading",
        type: "string",
        required: true,
        maxLength: 100,
        help: "Section heading above the game grid.",
      },
      {
        key: "title_codes",
        label: "Games",
        type: "title_code_list",
        required: true,
        maxItems: 24,
        help: "Select launchable titles. The backend validates each title against the catalog.",
      },
    ],
  },
  featured_game: {
    moduleCode: "featured_game",
    label: "Featured game",
    description: "One highlighted launchable game with optional editorial copy.",
    schemaVersion: 1,
    slotKeys: ["main", "feature"],
    fields: [
      {
        key: "title_code",
        label: "Featured title",
        type: "title_code",
        required: true,
        help: "The highlighted game title. Hidden or unavailable titles fail validation.",
      },
      {
        key: "headline",
        label: "Headline",
        type: "string",
        maxLength: 120,
        help: "Optional custom headline. If empty, the renderer can use the title name.",
      },
      {
        key: "body",
        label: "Body",
        type: "string",
        maxLength: 500,
        help: "Optional supporting copy for the featured game.",
      },
      {
        key: "cta_label",
        label: "CTA label",
        type: "string",
        maxLength: 60,
        help: "Optional button copy.",
      },
    ],
  },
  promo_band: {
    moduleCode: "promo_band",
    label: "Promo band",
    description: "Editorial promo strip with headline, body and CTA URL.",
    schemaVersion: 1,
    slotKeys: ["main", "promo"],
    fields: [
      {
        key: "headline",
        label: "Headline",
        type: "string",
        required: true,
        maxLength: 120,
        help: "Promo title shown in the public band.",
      },
      {
        key: "body",
        label: "Body",
        type: "string",
        maxLength: 500,
        help: "Promo description. Avoid legal or bonus promises not approved elsewhere.",
      },
      {
        key: "cta_label",
        label: "CTA label",
        type: "string",
        maxLength: 60,
        help: "Optional CTA text.",
      },
      {
        key: "cta_url",
        label: "CTA URL",
        type: "string",
        maxLength: 300,
        help: "Internal path or approved external URL. Backend validation is intentionally light in MVP.",
      },
    ],
  },
  rich_text_safe: {
    moduleCode: "rich_text_safe",
    label: "Rich text safe",
    description: "Allowlisted editorial HTML. The backend rejects unsafe tags and attributes.",
    schemaVersion: 1,
    slotKeys: ["main", "content", "footer"],
    fields: [
      {
        key: "html",
        label: "HTML",
        type: "html",
        required: true,
        maxLength: 12000,
        help: "Allowed tags: p, strong, em, ul, ol, li, a, br, h2, h3. No script/style/iframe.",
      },
    ],
  },
  global_footer: {
    moduleCode: "global_footer",
    label: "Global footer",
    description: "Footer legal text and link list shared by the public Site V3 pages.",
    schemaVersion: 1,
    slotKeys: ["footer"],
    fields: [
      {
        key: "legal_text",
        label: "Legal text",
        type: "string",
        required: true,
        maxLength: 1000,
        help: "Footer legal or responsible-gaming text.",
      },
      {
        key: "links",
        label: "Footer links",
        type: "nav_items",
        maxItems: 12,
        help: "One link per line: label | URL path. Max 12.",
      },
    ],
  },
};

export const SITE_V3_MODULE_CODES = Object.keys(SITE_V3_MODULE_DESCRIPTORS) as SiteV3ModuleCode[];
