"use client";

import type {
  SiteV3BuiltInModuleCode,
  SiteV3ModuleDefinition,
  SiteV3ModuleDescriptor,
  SiteV3ModuleFieldDescriptor,
} from "./site-v3-admin-types";

export const SITE_V3_MODULE_DESCRIPTORS: Record<SiteV3BuiltInModuleCode, SiteV3ModuleDescriptor> = {
  global_header: {
    moduleCode: "global_header",
    label: "Global header",
    category: "structure",
    description: "Brand header shared by the public Site V3 pages.",
    humanHint: "Use this for the site brand and account links. Usually one per page, placed at the top.",
    schemaVersion: 1,
    slotKeys: ["header"],
    fields: [
      {
        key: "brand_label",
        label: "Brand label",
        type: "string",
        group: "content",
        required: true,
        maxLength: 80,
        help: "Text shown as the site brand. Keep it short enough for mobile.",
      },
      {
        key: "login_label",
        label: "Login label",
        type: "string",
        group: "links",
        maxLength: 40,
        help: "Button copy linking to the Site V3 login route.",
      },
      {
        key: "account_label",
        label: "Account label",
        type: "string",
        group: "links",
        maxLength: 40,
        help: "Button copy linking to the Site V3 account route.",
      },
    ],
  },
  hero_banner: {
    moduleCode: "hero_banner",
    label: "Hero banner",
    category: "hero",
    description: "Primary homepage hero with headline, copy, CTA and optional media.",
    humanHint: "The main page banner. It can use a Site V3 media asset or fall back to the published V1 home banner.",
    schemaVersion: 1,
    slotKeys: ["main", "hero"],
    fields: [
      {
        key: "headline",
        label: "Headline",
        type: "string",
        group: "content",
        required: true,
        maxLength: 120,
        help: "Main headline. This is the first viewport message.",
      },
      {
        key: "body",
        label: "Body",
        type: "string",
        group: "content",
        maxLength: 500,
        help: "Supporting copy. Keep it concise and player-facing.",
      },
      {
        key: "cta_label",
        label: "CTA label",
        type: "string",
        group: "links",
        maxLength: 60,
        help: "Optional call-to-action text.",
      },
      {
        key: "cta_title_code",
        label: "CTA game",
        type: "title_code",
        group: "links",
        help: "Optional game title launched by the CTA. The backend validates the title.",
      },
      {
        key: "media_asset_ref",
        label: "Media asset",
        type: "asset_ref",
        group: "assets",
        help: "Optional banner asset. Pick a published Site media asset, or paste a public URL as fallback.",
      },
      {
        key: "show_copy",
        label: "Show copy",
        type: "boolean",
        group: "content",
        help: "Turn off to show only the banner image while keeping the CTA available.",
      },
      {
        key: "show_cta",
        label: "Show CTA",
        type: "boolean",
        group: "links",
        help: "Turn off to hide the banner button.",
      },
    ],
  },
  game_grid: {
    moduleCode: "game_grid",
    label: "Game grid",
    category: "catalog",
    description: "Grid of launchable game titles consumed from the live catalog.",
    humanHint: "The published game grid. Choose which title codes to show; the public order still follows the catalog.",
    schemaVersion: 1,
    slotKeys: ["main", "games"],
    fields: [
      {
        key: "heading",
        label: "Heading",
        type: "string",
        group: "content",
        required: true,
        maxLength: 100,
        help: "Heading above the game grid.",
      },
      {
        key: "title_codes",
        label: "Games",
        type: "title_code_list",
        group: "catalog",
        required: true,
        maxItems: 24,
        help: "Select launchable titles. The backend validates each title against the catalog.",
      },
    ],
  },
  game_grid_4x: {
    moduleCode: "game_grid_4x",
    label: "Grid$",
    category: "catalog",
    description: "Large four-column grid of launchable game titles.",
    humanHint: "Use this when game cards should be larger: four square cards per row on desktop, same catalog images.",
    schemaVersion: 1,
    slotKeys: ["main", "games"],
    fields: [
      {
        key: "heading",
        label: "Heading",
        type: "string",
        group: "content",
        required: true,
        maxLength: 100,
        help: "Heading above the large game grid.",
      },
      {
        key: "title_codes",
        label: "Games",
        type: "title_code_list",
        group: "catalog",
        required: true,
        maxItems: 24,
        help: "Select launchable titles. Rendered as four larger square cards per desktop row.",
      },
    ],
  },
  featured_game: {
    moduleCode: "featured_game",
    label: "Featured game",
    category: "catalog",
    description: "One highlighted launchable game with optional editorial copy.",
    humanHint: "One highlighted game, useful for promoting HI-LO, BOXE or a specific title variant.",
    schemaVersion: 1,
    slotKeys: ["main", "feature"],
    fields: [
      {
        key: "title_code",
        label: "Featured title",
        type: "title_code",
        group: "catalog",
        required: true,
        help: "The highlighted game title. Hidden or unavailable titles fail validation.",
      },
      {
        key: "headline",
        label: "Headline",
        type: "string",
        group: "content",
        maxLength: 120,
        help: "Optional custom headline. If empty, the renderer can use the title name.",
      },
      {
        key: "body",
        label: "Body",
        type: "string",
        group: "content",
        maxLength: 500,
        help: "Optional supporting copy for the featured game.",
      },
      {
        key: "cta_label",
        label: "CTA label",
        type: "string",
        group: "links",
        maxLength: 60,
        help: "Optional button copy.",
      },
    ],
  },
  promo_band: {
    moduleCode: "promo_band",
    label: "Promo band",
    category: "promo",
    description: "Editorial promo strip with headline, body and CTA URL.",
    humanHint: "A promotional or editorial strip. The MVP uses text and CTA only; upload remains in the asset area.",
    schemaVersion: 1,
    slotKeys: ["main", "promo"],
    fields: [
      {
        key: "headline",
        label: "Headline",
        type: "string",
        group: "content",
        required: true,
        maxLength: 120,
        help: "Promo title shown in the public band.",
      },
      {
        key: "body",
        label: "Body",
        type: "string",
        group: "content",
        maxLength: 500,
        help: "Promo description. Avoid legal or bonus promises not approved elsewhere.",
      },
      {
        key: "cta_label",
        label: "CTA label",
        type: "string",
        group: "links",
        maxLength: 60,
        help: "Optional CTA text.",
      },
      {
        key: "cta_url",
        label: "CTA URL",
        type: "string",
        group: "links",
        maxLength: 300,
        help: "Internal path or approved external URL. Backend validation is intentionally light in MVP.",
      },
    ],
  },
  system_registration_form: {
    moduleCode: "system_registration_form",
    label: "Registration form",
    category: "system",
    description: "System-owned registration route configuration consumed by the public /register page.",
    humanHint: "Mount this on the register system page to edit copy, field visibility and the document step without changing auth logic.",
    schemaVersion: 1,
    slotKeys: ["main", "system"],
    defaultConfig: {
      eyebrow: "Player",
      headline: "Registration",
      body: "Crea il tuo account player.",
      first_name_label: "First name",
      last_name_label: "Last name",
      fiscal_code_label: "Fiscal code",
      phone_number_label: "Phone number",
      email_label: "Email",
      password_label: "Password",
      access_code_label: "Access code",
      document_front_label: "Document front",
      document_back_label: "Document back",
      continue_label: "Continue",
      back_label: "Back",
      submit_label: "Complete registration",
      busy_label: "Completing...",
      login_label: "Sign in",
      lobby_label: "Back to lobby",
      checking_message: "Checking current player session.",
      authenticated_message: "You are already signed in. Opening your account.",
      authenticated_status: "Registration is available only before signing in.",
      document_upload_note:
        "Document images: PNG, JPEG, or WebP recommended, max 5 MB per side. Recommended 1600 x 1000 px or 1000 x 1600 px, matching document orientation. They are not rendered or resized yet; the backend does not store document files.",
      success_message: "Registration completed. Your document images will be requested again when backend upload is enabled.",
      legal_note_html: "",
      post_register_path: "/account",
      show_first_name: true,
      show_last_name: true,
      show_fiscal_code: true,
      show_phone_number: true,
      require_document_images: true,
    },
    fields: [
      {
        key: "eyebrow",
        label: "Eyebrow",
        type: "string",
        group: "content",
        maxLength: 60,
        help: "Small uppercase label above the form title.",
      },
      {
        key: "headline",
        label: "Headline",
        type: "string",
        group: "content",
        required: true,
        maxLength: 120,
        help: "Main registration title.",
      },
      {
        key: "body",
        label: "Body",
        type: "string",
        group: "content",
        maxLength: 500,
        help: "Short introduction above the registration fields.",
      },
      {
        key: "first_name_label",
        label: "First name label",
        type: "string",
        group: "content",
        maxLength: 80,
        help: "Label for the optional first-name field.",
      },
      {
        key: "last_name_label",
        label: "Last name label",
        type: "string",
        group: "content",
        maxLength: 80,
        help: "Label for the optional last-name field.",
      },
      {
        key: "fiscal_code_label",
        label: "Fiscal code label",
        type: "string",
        group: "content",
        maxLength: 80,
        help: "Label for the optional fiscal-code field.",
      },
      {
        key: "phone_number_label",
        label: "Phone number label",
        type: "string",
        group: "content",
        maxLength: 80,
        help: "Label for the optional phone-number field.",
      },
      {
        key: "email_label",
        label: "Email label",
        type: "string",
        group: "content",
        maxLength: 80,
        help: "Label for the required email field.",
      },
      {
        key: "password_label",
        label: "Password label",
        type: "string",
        group: "content",
        maxLength: 80,
        help: "Label for the required password field.",
      },
      {
        key: "access_code_label",
        label: "Access code label",
        type: "string",
        group: "content",
        maxLength: 80,
        help: "Label for the required site access password field.",
      },
      {
        key: "document_front_label",
        label: "Document front label",
        type: "string",
        group: "content",
        maxLength: 80,
        help: "Label for the front-side document picker.",
      },
      {
        key: "document_back_label",
        label: "Document back label",
        type: "string",
        group: "content",
        maxLength: 80,
        help: "Label for the back-side document picker.",
      },
      {
        key: "continue_label",
        label: "Continue label",
        type: "string",
        group: "links",
        maxLength: 80,
        help: "Step-one button copy when the document step is enabled.",
      },
      {
        key: "back_label",
        label: "Back label",
        type: "string",
        group: "links",
        maxLength: 80,
        help: "Button copy for returning from the document step.",
      },
      {
        key: "submit_label",
        label: "Submit label",
        type: "string",
        group: "links",
        maxLength: 80,
        help: "Final registration button copy.",
      },
      {
        key: "busy_label",
        label: "Busy label",
        type: "string",
        group: "links",
        maxLength: 80,
        help: "Button copy while registration is being submitted.",
      },
      {
        key: "login_label",
        label: "Login label",
        type: "string",
        group: "links",
        maxLength: 80,
        help: "Secondary link copy to the login route.",
      },
      {
        key: "lobby_label",
        label: "Lobby label",
        type: "string",
        group: "links",
        maxLength: 80,
        help: "Secondary link copy back to the lobby or return target.",
      },
      {
        key: "checking_message",
        label: "Checking message",
        type: "string",
        group: "content",
        maxLength: 200,
        help: "Message shown while the player session is checked.",
      },
      {
        key: "authenticated_message",
        label: "Authenticated message",
        type: "string",
        group: "content",
        maxLength: 200,
        help: "Message shown when a logged-in player opens registration.",
      },
      {
        key: "authenticated_status",
        label: "Authenticated status",
        type: "string",
        group: "content",
        maxLength: 200,
        help: "Status text shown when registration is blocked for logged-in players.",
      },
      {
        key: "document_upload_note",
        label: "Document note",
        type: "string",
        group: "rules",
        maxLength: 800,
        help: "Operational note above document image fields. Current backend does not persist uploaded files.",
      },
      {
        key: "success_message",
        label: "Success message",
        type: "string",
        group: "content",
        maxLength: 300,
        help: "Status message after registration succeeds, before redirect.",
      },
      {
        key: "legal_note_html",
        label: "Legal note HTML",
        type: "html",
        group: "rules",
        maxLength: 4000,
        help: "Optional allowlisted legal copy. This first slice does not persist consent records.",
      },
      {
        key: "post_register_path",
        label: "Post-register path",
        type: "url",
        group: "links",
        maxLength: 300,
        help: "Same-origin path used after registration when no return_to parameter is present.",
      },
      {
        key: "show_first_name",
        label: "Show first name",
        type: "boolean",
        group: "content",
        help: "Show or hide the optional first-name field.",
      },
      {
        key: "show_last_name",
        label: "Show last name",
        type: "boolean",
        group: "content",
        help: "Show or hide the optional last-name field.",
      },
      {
        key: "show_fiscal_code",
        label: "Show fiscal code",
        type: "boolean",
        group: "content",
        help: "Show or hide the optional fiscal-code field.",
      },
      {
        key: "show_phone_number",
        label: "Show phone number",
        type: "boolean",
        group: "content",
        help: "Show or hide the optional phone-number field.",
      },
      {
        key: "require_document_images",
        label: "Require document images",
        type: "boolean",
        group: "rules",
        help: "Keep the current document image gate before completion. This does not store files server-side yet.",
      },
    ],
  },
  rich_text_safe: {
    moduleCode: "rich_text_safe",
    label: "Rich text safe",
    category: "text_legal",
    description: "Allowlisted editorial HTML. The backend rejects unsafe tags and attributes.",
    humanHint: "Safe rich text for notes, rules, SEO or editorial content. HTML is filtered server-side.",
    schemaVersion: 1,
    slotKeys: ["main", "content", "footer"],
    fields: [
      {
        key: "html",
        label: "HTML",
        type: "html",
        group: "rules",
        required: true,
        maxLength: 12000,
        help: "Allowed tags: p, strong, em, ul, ol, li, a, br, h2, h3. No script/style/iframe.",
      },
    ],
  },
  global_footer: {
    moduleCode: "global_footer",
    label: "Global footer",
    category: "structure",
    description: "Footer legal text and link list shared by the public Site V3 pages.",
    humanHint: "Footer with legal text and links. Usually one per page, placed at the bottom.",
    schemaVersion: 1,
    slotKeys: ["footer"],
    fields: [
      {
        key: "legal_text",
        label: "Legal text",
        type: "string",
        group: "rules",
        required: true,
        maxLength: 1000,
        help: "Footer legal or responsible-gaming text.",
      },
      {
        key: "links",
        label: "Footer links",
        type: "nav_items",
        group: "links",
        maxItems: 12,
        help: "One link per line: label | URL path. Max 12.",
      },
    ],
  },
};

export const SITE_V3_MODULE_CODES = Object.keys(SITE_V3_MODULE_DESCRIPTORS) as SiteV3BuiltInModuleCode[];

export const SITE_V3_MODULE_CATEGORIES = [
  {
    key: "structure",
    label: "Global structure",
    description: "Shared page elements: header, navigation and footer.",
  },
  {
    key: "hero",
    label: "Hero and banners",
    description: "High-impact first-viewport modules for the main message.",
  },
  {
    key: "catalog",
    label: "Game catalog",
    description: "Modules connected to published titles and existing game cards in the catalog.",
  },
  {
    key: "promo",
    label: "Promos and editorial",
    description: "Promotional strips and lightweight editorial messages for the page.",
  },
  {
    key: "system",
    label: "System pages",
    description: "Route-owned modules for login, registration and account flows.",
  },
  {
    key: "text_legal",
    label: "Text and legal",
    description: "Safe text areas, notes, SEO content and legal content.",
  },
] as const;

export function customDefinitionToDescriptor(definition: SiteV3ModuleDefinition): SiteV3ModuleDescriptor | null {
  if (definition.status !== "published" || definition.published_version === null) {
    return null;
  }
  const label = definition.published_label ?? definition.label;
  const category = definition.published_category ?? definition.category;
  const rendererTemplate = definition.published_renderer_template ?? definition.renderer_template;
  const fields = definition.published_field_schema_json ?? definition.field_schema_json;
  const defaultConfig = definition.published_default_config_json ?? definition.default_config_json;
  return {
    moduleCode: definition.module_code,
    label,
    category,
    description: `Custom ${rendererTemplate} module.`,
    humanHint: `Custom module rendered by the approved ${rendererTemplate} template.`,
    schemaVersion: definition.published_version,
    slotKeys: slotKeysForCustomDefinition(category),
    fields: fields.map(customFieldToDescriptor),
    defaultConfig,
    custom: true,
  };
}

export function buildSiteV3ModuleDescriptors(
  definitions: SiteV3ModuleDefinition[],
): Record<string, SiteV3ModuleDescriptor> {
  const customEntries = definitions
    .map(customDefinitionToDescriptor)
    .filter((descriptor): descriptor is SiteV3ModuleDescriptor => descriptor !== null)
    .map((descriptor) => [descriptor.moduleCode, descriptor] as const);
  return {
    ...SITE_V3_MODULE_DESCRIPTORS,
    ...Object.fromEntries(customEntries),
  };
}

function customFieldToDescriptor(field: SiteV3ModuleDefinition["field_schema_json"][number]): SiteV3ModuleFieldDescriptor {
  return {
    key: field.key,
    label: field.label,
    type: field.type,
    group: field.group,
    required: field.required,
    maxLength: field.max_length,
    maxItems: field.max_items,
    help: field.help ?? "",
  };
}

function slotKeysForCustomDefinition(category: SiteV3ModuleDefinition["category"]): string[] {
  if (category === "hero") {
    return ["hero", "main"];
  }
  if (category === "catalog") {
    return ["games", "main"];
  }
  if (category === "promo") {
    return ["promo", "main"];
  }
  return ["content", "footer", "main"];
}
